// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfoaHo9G1Mdv4dNx_pF8avQ19wW2RrtaA',
    appId: '1:246053924162:web:1d43048cf85802eb766cdb',
    messagingSenderId: '246053924162',
    projectId: 'mess-2054c',
    authDomain: 'mess-2054c.firebaseapp.com',
    storageBucket: 'mess-2054c.appspot.com',
    measurementId: 'G-46F5YWHMLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDke7CUcIXEz9ZVjPWX-g8mns1QiFXuNI',
    appId: '1:246053924162:android:68785bc644db3d12766cdb',
    messagingSenderId: '246053924162',
    projectId: 'mess-2054c',
    storageBucket: 'mess-2054c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUnswfFYGWhXlb7xNGPWBAK8F9UEWmrU',
    appId: '1:246053924162:ios:b1970152a51e67ed766cdb',
    messagingSenderId: '246053924162',
    projectId: 'mess-2054c',
    storageBucket: 'mess-2054c.appspot.com',
    iosBundleId: 'com.example.demo',
  );
}
